// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArIF9uARJq3dP6SPSpfpDTz0dGc_8iF2o',
    appId: '1:472214943651:web:7f3425169c7f223e048c16',
    messagingSenderId: '472214943651',
    projectId: 'spotify-clone-firebase-bhondu',
    authDomain: 'spotify-clone-firebase-bhondu.firebaseapp.com',
    storageBucket: 'spotify-clone-firebase-bhondu.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4gONU0zBx31iuYWhoXbED5LdjcWjDiwM',
    appId: '1:472214943651:android:24c173c675ad9232048c16',
    messagingSenderId: '472214943651',
    projectId: 'spotify-clone-firebase-bhondu',
    storageBucket: 'spotify-clone-firebase-bhondu.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMys_tCbYz1hv39uSp-n8x9WZjLUogHvU',
    appId: '1:472214943651:ios:fb28510ff8a8a0cf048c16',
    messagingSenderId: '472214943651',
    projectId: 'spotify-clone-firebase-bhondu',
    storageBucket: 'spotify-clone-firebase-bhondu.firebasestorage.app',
    iosBundleId: 'com.example.spotifyClone',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMys_tCbYz1hv39uSp-n8x9WZjLUogHvU',
    appId: '1:472214943651:ios:fb28510ff8a8a0cf048c16',
    messagingSenderId: '472214943651',
    projectId: 'spotify-clone-firebase-bhondu',
    storageBucket: 'spotify-clone-firebase-bhondu.firebasestorage.app',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArIF9uARJq3dP6SPSpfpDTz0dGc_8iF2o',
    appId: '1:472214943651:web:00fba7be15588471048c16',
    messagingSenderId: '472214943651',
    projectId: 'spotify-clone-firebase-bhondu',
    authDomain: 'spotify-clone-firebase-bhondu.firebaseapp.com',
    storageBucket: 'spotify-clone-firebase-bhondu.firebasestorage.app',
  );
}
